### ISSUE TITLE
Proyecto4_Visualizacion_ArianneMurillo

### ISSUE THREAD

**Issue by Arimugon** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#1]
https://github.com/Arimugon/Proyecto4_Visualizacion.git

**Comment by AdrianCiges** [comment]
El repo genial organizado. Quizás decirte que ojees lo del tamaño de las imágenes, a veces puede que queden un poco pequeñas (opinión personal). 
El readme genial, investiga cómo añadir un índice de contenido para darle más riqueza.
Los gráficos guay, bien usados los diferentes tipos. Como consejo, reduce el volumen de texto tanto como puedes en algunas tablas y échale un ojo al color, que en el último gráfico puede perderse un poco con el fondo.
Muy buen trabajo. Keep going!
