### ISSUE TITLE
[Proyecto Visualización] Javier Garcia 

### ISSUE THREAD

**Issue by fjgarciaes** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#10]
https://github.com/fjgarciaes/Visualization-Proyect.git

https://public.tableau.com/app/profile/francisco.javier.garcia.escobar/viz/AnalisisSpotify_16689580547360/Historia1?publish=yes

**Comment by AdrianCiges** [comment]
El link a tableau mejor en el readme o en un archivo txt
El readme guay, pero mímalo un poco más, más visual y detallado. 
Has usado varios tipos de gráfico, muy bien por esa parte. 
Evita fondos blancos, dale caña al diseño y controla el espacio de la hoja el poner los gráficos para que no queden espacios vacíos. 
Buen trabajo, not bad!
