### ISSUE TITLE
[w5-Visualization-project] Jaime Manrique

### ISSUE THREAD

**Issue by Jaimemanrique** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#11]
https://public.tableau.com/app/profile/jaime.manrique/viz/J_J_O_ORo/Story1?publish=yes}

**Comment by AdrianCiges** [comment]
Not bad el readme, buen trabajo de visualización. 
Echaría en falta más gráficos, pero has usado diferentes tipos. Está guay.
En el issue debes poner el link a tu repo, no al tableau!
Well done en general.
