### ISSUE TITLE
[w5-Visualization-project] Aaron Nebreda

### ISSUE THREAD

**Issue by AaronNebreda** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#12]
https://github.com/AaronNebreda/-w5-Visualization-project

**Comment by AdrianCiges** [comment]
Buen repo, buen readme y el power BI está... bru-tal. Muy muy bonito, fácil de entender, buen diseño, bien organizado. Es que no te puedo decir nada. Tu progresión está siendo enorme y el cuidado que le está poniendo a tu trabajo es una marca personal ya. Eres un ejemplo, Aarón. Bravo.
