### ISSUE TITLE
[ w5-Visualization-project] Alicia Hernansanz

### ISSUE THREAD

**Issue by aliciahernansanz** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#13]
https://github.com/aliciahernansanz/Proyecto-VIZ

**Comment by AdrianCiges** [comment]
Guay el repo, te ha faltado una carpeta para la presentación. Cuidado con la última línea del readme que tiene una bombillita vacía por ahí. El readme por lo demás mola. Muy guay lo de hacerlo en inglés. Idiomas querida, aprende!
Como consejo, cámbiale el nombre a las capturas de pantalla y ponles algo tipo "Treemap de unis". 
En tu expo, yo hubiera puesto las unis en filas y los años en columnas en la tabla de la 1a diapo (más sencillo de ver) y en el de barras (al no haber decimales) me cargaría el .00. 
El resto genial, guay que uses varios tipos de gráficos. Buen trabajo.
