### ISSUE TITLE
[w5-Visualizacion-project] David Cuenca

### ISSUE THREAD

**Issue by kuenk** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#15]
Intento fallido para hacer visualización de los datos.

He tenido problemas con las relaciones en base de datos :( 
Podía haber puesto varios graficos por separado sin relacion logica entre ellos, pero no queria presentar el proyecto a medias

**Comment by kuenk** [comment]
https://github.com/kuenk/Mad-Scientist-2.0/blob/main/README.md

**Comment by AdrianCiges** [comment]
Recuerda poner el link al repo (no al readme) en la issue.
Bien usados varios gráficos. Controla el diseño, fondo, colores de los gráficos.
Organiza mejor el repo, metiendo cada archivo en su carpeta correspondiente: src para cógido, img para imagenes, etc.
Dale caña al readme, con su storytelling y unas pildoritas de los gráficos que se pueden ver en tu powerBi.
Keep going!
