### ISSUE TITLE
[w5-Visualization-project] "xabier"

### ISSUE THREAD

**Issue by XabierGarciaMartins** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#17]
https://github.com/XabierGarciaMartins/w5-Visualization-project.git

**Comment by OrianAmpuero** [comment]
Buen dashboard Xabi! Lo único es que el repo es clonado del nuestro y por eso tu readme es el de ironhack y por otra parte debes tener en el repo los datos de donde sacaste la visualización (un poco más de contenido)
