### ISSUE TITLE
[w5-Visualization-project] Jaime Muñoz

### ISSUE THREAD

**Issue by JIMYTHEONE** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#18]
https://github.com/JIMYTHEONE/PROYECT-VISUALIZATION.git

**Comment by OrianAmpuero** [comment]
Jaime! Sé que has tenido dificultades pero te ánimo nuevamente a seguir trabajado y esforzándote que merece la pena. Buen readme :)

Nota: Mira estos vídeos para complementar

1) Ejemplos de Dashboard con Power BI:
-Sencillo: https://www.youtube.com/watch?v=XvfrbZzWCzo
-Avanzado: https://www.youtube.com/watch?v=CO7pdrfDN6c

2) Ejemplos de Dashboard con Tableau:
-Sencillo: https://www.youtube.com/watch?v=th7ItYk68EM&t=303s
-Avanzado: https://www.youtube.com/watch?v=7UgU4Y_TWAU
