### ISSUE TITLE
[w5-Visualization-project] Alejandro Hornero

### ISSUE THREAD

**Issue by Baker-man** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#2]
https://github.com/Baker-man/Proyecto-Viz

**Comment by AdrianCiges** [comment]
Buen repo, bien organizado. La presentación recuerda ponerla en una carpeta para ella (tipo ppt, o presentación). 
El readme bravo, muy bien. Como detalle, dale un nombre al archivo de powerBI, cuidado con los colores condicionales en el gráfico de barras que lo has puesto como recuento de tipo de accidente y lo suyo sería que fuera por número de expediente, que es lo que estás usando para el conteo. 
El power BI mola, muy muy buen trabajo!
