### ISSUE TITLE
[w5-Visualization-project] Pablo Galán

### ISSUE THREAD

**Issue by pablogalann** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#20]
https://github.com/pablogalann/5.5-Proyecto-Viz-Pablo-Galan.git

**Comment by OrianAmpuero** [comment]
Te animo a mejorar el readme y tener todo mejor organizado en cuanto a los datos; por otra parte, no pude entrar en tu dashboard así que miralo para que lo tengas dentro de tu repo
