### ISSUE TITLE
[w5-Visualization-project] Álvaro Diego

### ISSUE THREAD

**Issue by Varoo97** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#22]
https://github.com/Varoo97/Proyecto-Visualizaci-n.git

**Comment by AdrianCiges** [comment]
Organiza el repo por carpetas. 
El readme te ha quedado desorganizado. No se han ejecutado los saltos de línea. Investiga cómo escribirlos 🔎. 
La 2a página del powerBI va por buen camino, te faltaría ver de cambiar el fondo de pantalla, probar el formato condicional de colores en el gráfico de barras (por ejemplo), pero la primera página es, honestamente, un desastre. Imagino que la dejaste a medias por cualquier cosa, pero cuidado con eso porque puede dar mala imagen. Termínala o cárgatela, illo.
