### ISSUE TITLE
[w5-Visualization-project] Iñigo Larrea

### ISSUE THREAD

**Issue by pombo7676** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#23]
https://github.com/pombo7676/w5-Visualization-project.Power.BI.git

**Comment by AdrianCiges** [comment]
El trabajo de gráficos está bien, PERO:
-No hay readme. Una de las condiciones que dijo Yona era que en el readme escribierais el storytelling. Aun así, aunque no lo hubiera dicho, no puedes dejarlo sin readme!
-El curro de gráficos bien, pero controla el espacio de las hojas. hay gráficos montados encima de otros y a veces da sensación de amontonado.
-Cuida más el diseño, el fondo, los colores, etc.

**Comment by pombo7676** [comment]
Gracias por los consejos Adri.

Ya he trabajado un poco el Readme y he modificado un poco los dashboards.

Porfa échale un vistazo rápido a mi repo y a ver que te parece.

https://github.com/pombo7676/w5-Visualization-project.Power.BI.git

P.D. Sigue montándose un cuadro del último dashboard echo aposta  jejeje ;)
