### ISSUE TITLE
[w5-Visualization-project] David Tejedor

### ISSUE THREAD

**Issue by Davidteje** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#4]
https://github.com/Davidteje/w5-Visualization-project

**Comment by AdrianCiges** [comment]
El repo genial, muy bien organizado. El readme muy claro, muy visual y explicado todo. 
El link de tableau lo podría arriba del todo o en un txt. 
Los colores guay, muy coherente durante toda la expo, pero como opinión personal, quizá un poco serios para estar hablando de futbol no?
Muy buena variedad de gráficos y muy top los mapas de calor.
Muy buen trabajo, David
