### ISSUE TITLE
[w5-Visualization-project] Arturo

### ISSUE THREAD

**Issue by Artturoo** [Ironhack-Data-Madrid-Octubre-2022/w5-Visualization-project#7]
https://github.com/Artturoo/w5-Visualization-project.git

**Comment by AdrianCiges** [comment]
Detalles:
-El link a tableau no lo meetería en src, ya que esa suele ser para código.
-Ele readme genial, aunque echo en falta ver algún gráfico o iconos que señalicen las secciones.
-Los gráficos guay, como detalle investiga como poner en horizontal los números del gráfico de barras.
Buen trabajo ;)
